/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/aero.glb 
Author: themaker845 (https://sketchfab.com/themaker845)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-787-dreamliner-524f485c748146b7968e0dd8eb84e786
Title: Boeing-787- Dreamliner
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export function Aero(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/aero.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.894}>
          <group name="Root">
            <group name="Boeing_787_Dreamliner001" position={[-0.213, -1.631, 0.058]} scale={0.401}>
              <group name="Zylinder001" position={[1.608, -0.157, -0.506]} rotation={[0.272, -1.508, -1.287]} scale={-1}>
                <mesh name="Zylinder001_0" geometry={nodes.Zylinder001_0.geometry} material={materials['Material.055']} />
                <mesh name="Zylinder001_1" geometry={nodes.Zylinder001_1.geometry} material={materials['BMD_Rubber_0004.002']} />
                <mesh name="Zylinder001_2" geometry={nodes.Zylinder001_2.geometry} material={materials['Material.056']} />
              </group>
              <group name="Zylinder000" position={[-3.456, 3.479, -0.868]} rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
                <mesh name="Zylinder000_0" geometry={nodes.Zylinder000_0.geometry} material={materials['Material.469']} />
                <mesh name="Zylinder000_1" geometry={nodes.Zylinder000_1.geometry} material={materials['Material.470']} />
                <mesh name="Zylinder000_2" geometry={nodes.Zylinder000_2.geometry} material={materials['Material.471']} />
                <mesh name="Zylinder000_3" geometry={nodes.Zylinder000_3.geometry} material={materials['Material.472']} />
              </group>
              <group name="Zylinder004" position={[3.454, 3.479, -0.85]} rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
                <mesh name="Zylinder004_0" geometry={nodes.Zylinder004_0.geometry} material={materials['Material.469']} />
                <mesh name="Zylinder004_1" geometry={nodes.Zylinder004_1.geometry} material={materials['Material.470']} />
                <mesh name="Zylinder004_2" geometry={nodes.Zylinder004_2.geometry} material={materials['Material.471']} />
                <mesh name="Zylinder004_3" geometry={nodes.Zylinder004_3.geometry} material={materials['Material.472']} />
              </group>
              <group name="Zylinder005" position={[-1.604, -0.263, -0.417]} rotation={[1.587, 0.032, 1.543]}>
                <mesh name="Zylinder005_0" geometry={nodes.Zylinder005_0.geometry} material={materials['Material.055']} />
                <mesh name="Zylinder005_1" geometry={nodes.Zylinder005_1.geometry} material={materials['BMD_Rubber_0004.002']} />
                <mesh name="Zylinder005_2" geometry={nodes.Zylinder005_2.geometry} material={materials['Material.056']} />
              </group>
              <group name="Zylinder006" position={[0.009, 4.812, -0.082]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh name="Zylinder006_0" geometry={nodes.Zylinder006_0.geometry} material={materials['Material.057']} />
                <mesh name="Zylinder006_1" geometry={nodes.Zylinder006_1.geometry} material={materials['Material.058']} />
                <mesh name="Zylinder006_2" geometry={nodes.Zylinder006_2.geometry} material={materials['Material.059']} />
              </group>
              <group name="Zylinder007" position={[0.002, 7.893, -0.655]} rotation={[1.477, 0, Math.PI / 2]}>
                <mesh name="Zylinder007_0" geometry={nodes.Zylinder007_0.geometry} material={materials['Material.055']} />
                <mesh name="Zylinder007_1" geometry={nodes.Zylinder007_1.geometry} material={materials['BMD_Rubber_0004.002']} />
                <mesh name="Zylinder007_2" geometry={nodes.Zylinder007_2.geometry} material={materials['Material.056']} />
              </group>
              <mesh name="Boeing_787_Dreamliner001_0" geometry={nodes.Boeing_787_Dreamliner001_0.geometry} material={materials.Interior_gray} />
              <mesh name="Boeing_787_Dreamliner001_1" geometry={nodes.Boeing_787_Dreamliner001_1.geometry} material={materials.Light_A} />
              <mesh name="Boeing_787_Dreamliner001_2" geometry={nodes.Boeing_787_Dreamliner001_2.geometry} material={materials.Inetrior_Blue} />
              <mesh name="Boeing_787_Dreamliner001_3" geometry={nodes.Boeing_787_Dreamliner001_3.geometry} material={materials.Outside_Right} />
              <mesh name="Boeing_787_Dreamliner001_4" geometry={nodes.Boeing_787_Dreamliner001_4.geometry} material={materials.Glass} />
              <mesh name="Boeing_787_Dreamliner001_5" geometry={nodes.Boeing_787_Dreamliner001_5.geometry} material={materials.Interior_wight} />
              <mesh name="Boeing_787_Dreamliner001_6" geometry={nodes.Boeing_787_Dreamliner001_6.geometry} material={materials.Cockpit_black} />
              <mesh name="Boeing_787_Dreamliner001_7" geometry={nodes.Boeing_787_Dreamliner001_7.geometry} material={materials['Cockpit_gray.001']} />
              <mesh name="Boeing_787_Dreamliner001_8" geometry={nodes.Boeing_787_Dreamliner001_8.geometry} material={materials.Cockpit_gray} />
              <mesh name="Boeing_787_Dreamliner001_9" geometry={nodes.Boeing_787_Dreamliner001_9.geometry} material={materials.COkpit_black} />
              <mesh name="Boeing_787_Dreamliner001_10" geometry={nodes.Boeing_787_Dreamliner001_10.geometry} material={materials.Cockpit_blue} />
              <mesh name="Boeing_787_Dreamliner001_11" geometry={nodes.Boeing_787_Dreamliner001_11.geometry} material={materials.Cockpit_chair_gray} />
              <mesh name="Boeing_787_Dreamliner001_12" geometry={nodes.Boeing_787_Dreamliner001_12.geometry} material={materials.Storage} />
              <mesh name="Boeing_787_Dreamliner001_13" geometry={nodes.Boeing_787_Dreamliner001_13.geometry} material={materials.Light_red} />
              <mesh name="Boeing_787_Dreamliner001_14" geometry={nodes.Boeing_787_Dreamliner001_14.geometry} material={materials.light_green} />
              <mesh name="Boeing_787_Dreamliner001_15" geometry={nodes.Boeing_787_Dreamliner001_15.geometry} material={materials.Floor} />
              <mesh name="Boeing_787_Dreamliner001_16" geometry={nodes.Boeing_787_Dreamliner001_16.geometry} material={materials.Chair_blue} />
              <mesh name="Boeing_787_Dreamliner001_17" geometry={nodes.Boeing_787_Dreamliner001_17.geometry} material={materials.Cjair_gray} />
              <mesh name="Boeing_787_Dreamliner001_18" geometry={nodes.Boeing_787_Dreamliner001_18.geometry} material={materials.Chair_black} />
              <mesh name="Boeing_787_Dreamliner001_19" geometry={nodes.Boeing_787_Dreamliner001_19.geometry} material={materials.white} />
              <mesh name="Boeing_787_Dreamliner001_20" geometry={nodes.Boeing_787_Dreamliner001_20.geometry} material={materials.Outsinde_left} />
              <mesh name="Boeing_787_Dreamliner001_21" geometry={nodes.Boeing_787_Dreamliner001_21.geometry} material={materials.outside_glossy} />
              <mesh name="Boeing_787_Dreamliner001_22" geometry={nodes.Boeing_787_Dreamliner001_22.geometry} material={materials['Cockpit_texture.001']} />
              <mesh name="Boeing_787_Dreamliner001_23" geometry={nodes.Boeing_787_Dreamliner001_23.geometry} material={materials['Cockpit_texture.002']} />
              <mesh name="Boeing_787_Dreamliner001_24" geometry={nodes.Boeing_787_Dreamliner001_24.geometry} material={materials.Cockpit_texture} />
            </group>
            <group name="Plane" position={[-0.516, 0.058, -0.736]} rotation={[0, 0, -Math.PI]} scale={-5.491}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials.BakedCycles} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/aero.glb')
