/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/city.glb 
Author: vanogetashvili (https://sketchfab.com/vanogetashvili)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/city-test-39847201bf9f4338a76ba39a53b5da1f
Title: city test
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function City(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/city.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[361041.969, -52298.43, 0]} rotation={[Math.PI / 2, -0.007, -Math.PI]}>
          <group name="MOSCOW_TESTFBX" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Group003" position={[101304.773, 152841.875, 1163.719]} rotation={[0.029, 1.047, 1.538]} scale={0.79}>
                  <group name="Group002" position={[74230.781, -109075.359, 188924.063]} scale={92.945}>
                    <group name="Group001" position={[-924.357, 757.352, 1436.709]}>
                      <group name="Box001" position={[-20.128, -108.791, -2560.641]}>
                        <mesh name="Box001_roads_secondary_0" geometry={nodes.Box001_roads_secondary_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roads_motorway_0" geometry={nodes.Box001_roads_motorway_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_wall_0" geometry={nodes.Box001_wall_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_wall_0_1" geometry={nodes.Box001_wall_0_1.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_wall_0_2" geometry={nodes.Box001_wall_0_2.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_vegetation_0" geometry={nodes.Box001_vegetation_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roads_unclassified_0" geometry={nodes.Box001_roads_unclassified_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roads_trunk_0" geometry={nodes.Box001_roads_trunk_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roads_service_0" geometry={nodes.Box001_roads_service_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roads_residential_0" geometry={nodes.Box001_roads_residential_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roads_primary_0" geometry={nodes.Box001_roads_primary_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roads_pedestrian_0" geometry={nodes.Box001_roads_pedestrian_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_paths_footway_0" geometry={nodes.Box001_paths_footway_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_forest_0" geometry={nodes.Box001_forest_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_roof_0" geometry={nodes.Box001_roof_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_lightgrey_0" geometry={nodes.Box001_lightgrey_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_areas_service_0" geometry={nodes.Box001_areas_service_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_areas_pedestrian_0" geometry={nodes.Box001_areas_pedestrian_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="Box001_areas_footway_0" geometry={nodes.Box001_areas_footway_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                      </group>
                    </group>
                    <group name="T" position={[-924.357, 757.352, 1436.709]}>
                      <group name="Object_263" position={[-20.128, -108.791, -2560.641]}>
                        <mesh name="T_f8f8fa_0" geometry={nodes.T_f8f8fa_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="T_cccfdb_0" geometry={nodes.T_cccfdb_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="T_roof_0" geometry={nodes.T_roof_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="T_9cb1d2_0" geometry={nodes.T_9cb1d2_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="T_wall_0" geometry={nodes.T_wall_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="T_wall_0_1" geometry={nodes.T_wall_0_1.geometry} material={materials['MOSCOW_TEST.FBX']} />
                        <mesh name="T_51556a_0" geometry={nodes.T_51556a_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                      </group>
                    </group>
                  </group>
                  <group name="bloks" position={[-11683.563, -38683.309, 322458.813]} scale={92.945}>
                    <mesh name="bloks_bloks_mat_0" geometry={nodes.bloks_bloks_mat_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                  </group>
                  <group name="Object001" position={[-11683.563, -38683.309, 322458.813]} scale={92.945}>
                    <group name="Object_274" position={[-20.128, -108.791, -2560.641]}>
                      <mesh name="Object001_BLD_0" geometry={nodes.Object001_BLD_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                    </group>
                  </group>
                </group>
                <group name="Cube" scale={100}>
                  <mesh name="Cube_Material_0" geometry={nodes.Cube_Material_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_buildings" scale={100}>
                  <mesh name="map_(1)osm_buildings_wall_0" geometry={nodes['map_(1)osm_buildings_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(1)osm_buildings_roof_0" geometry={nodes['map_(1)osm_buildings_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_water" position={[0, 0, 20]} scale={100}>
                  <mesh name="map_(1)osm_water_water_0" geometry={nodes['map_(1)osm_water_water_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_vegetation" scale={100}>
                  <mesh name="map_(1)osm_vegetation_vegetation_0" geometry={nodes['map_(1)osm_vegetation_vegetation_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_areas_pedestrian" scale={100}>
                  <mesh name="map_(1)osm_areas_pedestrian_areas_pedestrian_0" geometry={nodes['map_(1)osm_areas_pedestrian_areas_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_areas_service" scale={100}>
                  <mesh name="map_(1)osm_areas_service_areas_service_0" geometry={nodes['map_(1)osm_areas_service_areas_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_forest" position={[0, 0, 10]} scale={100}>
                  <mesh name="map_(1)osm_forest_forest_0" geometry={nodes['map_(1)osm_forest_forest_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_roads_secondary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_roads_secondary_roads_secondary_0" geometry={nodes['map_(1)osm_roads_secondary_roads_secondary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_paths_footway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_paths_footway_paths_footway_0" geometry={nodes['map_(1)osm_paths_footway_paths_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_roads_primary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_roads_primary_roads_primary_0" geometry={nodes['map_(1)osm_roads_primary_roads_primary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_roads_tertiary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_roads_tertiary_roads_tertiary_0" geometry={nodes['map_(1)osm_roads_tertiary_roads_tertiary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_roads_residential" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_roads_residential_roads_residential_0" geometry={nodes['map_(1)osm_roads_residential_roads_residential_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_roads_unclassified" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_roads_unclassified_roads_unclassified_0" geometry={nodes['map_(1)osm_roads_unclassified_roads_unclassified_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_roads_service" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_roads_service_roads_service_0" geometry={nodes['map_(1)osm_roads_service_roads_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_paths_steps" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_paths_steps_paths_steps_0" geometry={nodes['map_(1)osm_paths_steps_paths_steps_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_roads_track" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(1)osm_roads_track_roads_track_0" geometry={nodes['map_(1)osm_roads_track_roads_track_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_areas_footway" scale={100}>
                  <mesh name="map_(1)osm_areas_footway_areas_footway_0" geometry={nodes['map_(1)osm_areas_footway_areas_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="profile_roads_primary" position={[0, 1323.994, 0]} scale={100} />
                <group name="profile_roads_secondary" position={[0, 1194.026, 0]} scale={100} />
                <group name="profile_roads_tertiary" position={[0, 1041.121, 0]} scale={100} />
                <group name="profile_roads_unclassified" position={[0, 880.572, 0]} scale={100} />
                <group name="profile_roads_residential" position={[0, 697.087, 0]} scale={100} />
                <group name="profile_paths_footway" position={[0, 448.919, 0]} scale={100} />
                <group name="profile_roads_service" position={[0, 356.768, 0]} scale={100} />
                <group name="profile_roads_track" position={[0, 156.694, 0]} scale={100} />
                <group name="profile_paths_steps" position={[0, 96.782, 0]} scale={100} />
                <group name="profile_paths_bridleway" position={[0, -75.531, 0]} scale={100} />
                <group name="profile_roads_pedestrian" position={[0, 247.93, 0]} scale={100} />
                <group name="profile_paths_cycleway" position={[0, 26.839, 0]} scale={100} />
                <group name="map_(3)osm_buildings" scale={100}>
                  <mesh name="map_(3)osm_buildings_wall_0" geometry={nodes['map_(3)osm_buildings_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(3)osm_buildings_roof_0" geometry={nodes['map_(3)osm_buildings_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(3)osm_buildings_af8760_0" geometry={nodes['map_(3)osm_buildings_af8760_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_vegetation" scale={100}>
                  <mesh name="map_(3)osm_vegetation_vegetation_0" geometry={nodes['map_(3)osm_vegetation_vegetation_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_forest" position={[0, 0, 10]} scale={100}>
                  <mesh name="map_(3)osm_forest_forest_0" geometry={nodes['map_(3)osm_forest_forest_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_roads_unclassified" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_roads_unclassified_roads_unclassified_0" geometry={nodes['map_(3)osm_roads_unclassified_roads_unclassified_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_roads_residential" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_roads_residential_roads_residential_0" geometry={nodes['map_(3)osm_roads_residential_roads_residential_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_roads_tertiary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_roads_tertiary_roads_tertiary_0" geometry={nodes['map_(3)osm_roads_tertiary_roads_tertiary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_roads_primary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_roads_primary_roads_primary_0" geometry={nodes['map_(3)osm_roads_primary_roads_primary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_roads_secondary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_roads_secondary_roads_secondary_0" geometry={nodes['map_(3)osm_roads_secondary_roads_secondary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_roads_service" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_roads_service_roads_service_0" geometry={nodes['map_(3)osm_roads_service_roads_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_paths_steps" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_paths_steps_paths_steps_0" geometry={nodes['map_(3)osm_paths_steps_paths_steps_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_paths_footway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_paths_footway_paths_footway_0" geometry={nodes['map_(3)osm_paths_footway_paths_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(3)osm_paths_bridleway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(3)osm_paths_bridleway_paths_bridleway_0" geometry={nodes['map_(3)osm_paths_bridleway_paths_bridleway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_buildings" scale={100}>
                  <mesh name="map_(4)osm_buildings_wall_0" geometry={nodes['map_(4)osm_buildings_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(4)osm_buildings_roof_0" geometry={nodes['map_(4)osm_buildings_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(4)osm_buildings_white_0" geometry={nodes['map_(4)osm_buildings_white_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_vegetation" scale={100}>
                  <mesh name="map_(4)osm_vegetation_vegetation_0" geometry={nodes['map_(4)osm_vegetation_vegetation_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_forest" position={[0, 0, 10]} scale={100}>
                  <mesh name="map_(4)osm_forest_forest_0" geometry={nodes['map_(4)osm_forest_forest_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_water" position={[0, 0, 20]} scale={100}>
                  <mesh name="map_(4)osm_water_water_0" geometry={nodes['map_(4)osm_water_water_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_areas_pedestrian" scale={100}>
                  <mesh name="map_(4)osm_areas_pedestrian_areas_pedestrian_0" geometry={nodes['map_(4)osm_areas_pedestrian_areas_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_roads_primary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_roads_primary_roads_primary_0" geometry={nodes['map_(4)osm_roads_primary_roads_primary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_roads_residential" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_roads_residential_roads_residential_0" geometry={nodes['map_(4)osm_roads_residential_roads_residential_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_roads_unclassified" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_roads_unclassified_roads_unclassified_0" geometry={nodes['map_(4)osm_roads_unclassified_roads_unclassified_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_roads_secondary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_roads_secondary_roads_secondary_0" geometry={nodes['map_(4)osm_roads_secondary_roads_secondary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_paths_footway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_paths_footway_paths_footway_0" geometry={nodes['map_(4)osm_paths_footway_paths_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_roads_tertiary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_roads_tertiary_roads_tertiary_0" geometry={nodes['map_(4)osm_roads_tertiary_roads_tertiary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_roads_pedestrian" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_roads_pedestrian_roads_pedestrian_0" geometry={nodes['map_(4)osm_roads_pedestrian_roads_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_roads_service" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_roads_service_roads_service_0" geometry={nodes['map_(4)osm_roads_service_roads_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_paths_steps" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_paths_steps_paths_steps_0" geometry={nodes['map_(4)osm_paths_steps_paths_steps_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_areas_footway" scale={100}>
                  <mesh name="map_(4)osm_areas_footway_areas_footway_0" geometry={nodes['map_(4)osm_areas_footway_areas_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_paths_cycleway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(4)osm_paths_cycleway_paths_cycleway_0" geometry={nodes['map_(4)osm_paths_cycleway_paths_cycleway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(4)osm_areas_service" scale={100}>
                  <mesh name="map_(4)osm_areas_service_areas_service_0" geometry={nodes['map_(4)osm_areas_service_areas_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_buildings" scale={100}>
                  <mesh name="map_(5)osm_buildings_wall_0" geometry={nodes['map_(5)osm_buildings_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(5)osm_buildings_roof_0" geometry={nodes['map_(5)osm_buildings_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(5)osm_buildings_037bbf_0" geometry={nodes['map_(5)osm_buildings_037bbf_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_vegetation" scale={100}>
                  <mesh name="map_(5)osm_vegetation_vegetation_0" geometry={nodes['map_(5)osm_vegetation_vegetation_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_forest" position={[0, 0, 10]} scale={100}>
                  <mesh name="map_(5)osm_forest_forest_0" geometry={nodes['map_(5)osm_forest_forest_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_areas_service" scale={100}>
                  <mesh name="map_(5)osm_areas_service_areas_service_0" geometry={nodes['map_(5)osm_areas_service_areas_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_water" position={[0, 0, 20]} scale={100}>
                  <mesh name="map_(5)osm_water_water_0" geometry={nodes['map_(5)osm_water_water_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_roads_tertiary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_roads_tertiary_roads_tertiary_0" geometry={nodes['map_(5)osm_roads_tertiary_roads_tertiary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_roads_secondary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_roads_secondary_roads_secondary_0" geometry={nodes['map_(5)osm_roads_secondary_roads_secondary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_roads_unclassified" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_roads_unclassified_roads_unclassified_0" geometry={nodes['map_(5)osm_roads_unclassified_roads_unclassified_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_roads_service" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_roads_service_roads_service_0" geometry={nodes['map_(5)osm_roads_service_roads_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_roads_residential" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_roads_residential_roads_residential_0" geometry={nodes['map_(5)osm_roads_residential_roads_residential_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_roads_pedestrian" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_roads_pedestrian_roads_pedestrian_0" geometry={nodes['map_(5)osm_roads_pedestrian_roads_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_paths_footway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_paths_footway_paths_footway_0" geometry={nodes['map_(5)osm_paths_footway_paths_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_paths_steps" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_paths_steps_paths_steps_0" geometry={nodes['map_(5)osm_paths_steps_paths_steps_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_areas_pedestrian" scale={100}>
                  <mesh name="map_(5)osm_areas_pedestrian_areas_pedestrian_0" geometry={nodes['map_(5)osm_areas_pedestrian_areas_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(5)osm_paths_cycleway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(5)osm_paths_cycleway_paths_cycleway_0" geometry={nodes['map_(5)osm_paths_cycleway_paths_cycleway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_buildings" scale={100}>
                  <mesh name="map_(6)osm_buildings_wall_0" geometry={nodes['map_(6)osm_buildings_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(6)osm_buildings_roof_0" geometry={nodes['map_(6)osm_buildings_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(6)osm_buildings_gray_0" geometry={nodes['map_(6)osm_buildings_gray_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_vegetation" scale={100}>
                  <mesh name="map_(6)osm_vegetation_vegetation_0" geometry={nodes['map_(6)osm_vegetation_vegetation_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_water" position={[0, 0, 20]} scale={100}>
                  <mesh name="map_(6)osm_water_water_0" geometry={nodes['map_(6)osm_water_water_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_roads_pedestrian" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_roads_pedestrian_roads_pedestrian_0" geometry={nodes['map_(6)osm_roads_pedestrian_roads_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_roads_unclassified" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_roads_unclassified_roads_unclassified_0" geometry={nodes['map_(6)osm_roads_unclassified_roads_unclassified_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_roads_residential" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_roads_residential_roads_residential_0" geometry={nodes['map_(6)osm_roads_residential_roads_residential_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_roads_primary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_roads_primary_roads_primary_0" geometry={nodes['map_(6)osm_roads_primary_roads_primary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_roads_tertiary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_roads_tertiary_roads_tertiary_0" geometry={nodes['map_(6)osm_roads_tertiary_roads_tertiary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_roads_secondary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_roads_secondary_roads_secondary_0" geometry={nodes['map_(6)osm_roads_secondary_roads_secondary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_roads_service" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_roads_service_roads_service_0" geometry={nodes['map_(6)osm_roads_service_roads_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_paths_footway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_paths_footway_paths_footway_0" geometry={nodes['map_(6)osm_paths_footway_paths_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_paths_steps" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(6)osm_paths_steps_paths_steps_0" geometry={nodes['map_(6)osm_paths_steps_paths_steps_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_forest" position={[0, 0, 10]} scale={100}>
                  <mesh name="map_(6)osm_forest_forest_0" geometry={nodes['map_(6)osm_forest_forest_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(6)osm_areas_service" scale={100}>
                  <mesh name="map_(6)osm_areas_service_areas_service_0" geometry={nodes['map_(6)osm_areas_service_areas_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_buildings" scale={100}>
                  <mesh name="map_(7)osm_buildings_wall_0" geometry={nodes['map_(7)osm_buildings_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(7)osm_buildings_roof_0" geometry={nodes['map_(7)osm_buildings_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(7)osm_buildings_silver_0" geometry={nodes['map_(7)osm_buildings_silver_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_vegetation" scale={100}>
                  <mesh name="map_(7)osm_vegetation_vegetation_0" geometry={nodes['map_(7)osm_vegetation_vegetation_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_water" position={[0, 0, 20]} scale={100}>
                  <mesh name="map_(7)osm_water_water_0" geometry={nodes['map_(7)osm_water_water_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_roads_primary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_roads_primary_roads_primary_0" geometry={nodes['map_(7)osm_roads_primary_roads_primary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_roads_pedestrian" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_roads_pedestrian_roads_pedestrian_0" geometry={nodes['map_(7)osm_roads_pedestrian_roads_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_roads_unclassified" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_roads_unclassified_roads_unclassified_0" geometry={nodes['map_(7)osm_roads_unclassified_roads_unclassified_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_roads_residential" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_roads_residential_roads_residential_0" geometry={nodes['map_(7)osm_roads_residential_roads_residential_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_roads_tertiary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_roads_tertiary_roads_tertiary_0" geometry={nodes['map_(7)osm_roads_tertiary_roads_tertiary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_roads_secondary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_roads_secondary_roads_secondary_0" geometry={nodes['map_(7)osm_roads_secondary_roads_secondary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_roads_service" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_roads_service_roads_service_0" geometry={nodes['map_(7)osm_roads_service_roads_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_paths_footway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_paths_footway_paths_footway_0" geometry={nodes['map_(7)osm_paths_footway_paths_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_paths_steps" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(7)osm_paths_steps_paths_steps_0" geometry={nodes['map_(7)osm_paths_steps_paths_steps_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_forest" position={[0, 0, 10]} scale={100}>
                  <mesh name="map_(7)osm_forest_forest_0" geometry={nodes['map_(7)osm_forest_forest_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(7)osm_areas_pedestrian" scale={100}>
                  <mesh name="map_(7)osm_areas_pedestrian_areas_pedestrian_0" geometry={nodes['map_(7)osm_areas_pedestrian_areas_pedestrian_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_buildings" scale={100}>
                  <mesh name="map_(8)osm_buildings_wall_0" geometry={nodes['map_(8)osm_buildings_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(8)osm_buildings_roof_0" geometry={nodes['map_(8)osm_buildings_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_vegetation" scale={100}>
                  <mesh name="map_(8)osm_vegetation_vegetation_0" geometry={nodes['map_(8)osm_vegetation_vegetation_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_roads_secondary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_roads_secondary_roads_secondary_0" geometry={nodes['map_(8)osm_roads_secondary_roads_secondary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_roads_service" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_roads_service_roads_service_0" geometry={nodes['map_(8)osm_roads_service_roads_service_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_roads_tertiary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_roads_tertiary_roads_tertiary_0" geometry={nodes['map_(8)osm_roads_tertiary_roads_tertiary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_roads_residential" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_roads_residential_roads_residential_0" geometry={nodes['map_(8)osm_roads_residential_roads_residential_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_roads_unclassified" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_roads_unclassified_roads_unclassified_0" geometry={nodes['map_(8)osm_roads_unclassified_roads_unclassified_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_roads_primary" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_roads_primary_roads_primary_0" geometry={nodes['map_(8)osm_roads_primary_roads_primary_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_paths_footway" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_paths_footway_paths_footway_0" geometry={nodes['map_(8)osm_paths_footway_paths_footway_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_paths_steps" position={[0, 0, 30]} scale={100}>
                  <mesh name="map_(8)osm_paths_steps_paths_steps_0" geometry={nodes['map_(8)osm_paths_steps_paths_steps_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(8)osm_forest" position={[0, 0, 10]} scale={100}>
                  <mesh name="map_(8)osm_forest_forest_0" geometry={nodes['map_(8)osm_forest_forest_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="Compass001" position={[204603.938, -15304.725, 0]} />
                <group name="map_(1)osm_buildings001" position={[369289.531, -33436.313, 0]} rotation={[0, 0, -0.235]} scale={100}>
                  <mesh name="map_(1)osm_buildings001_wall_0" geometry={nodes['map_(1)osm_buildings001_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(1)osm_buildings001_roof_0" geometry={nodes['map_(1)osm_buildings001_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="map_(1)osm_buildings003" position={[377308.313, 115339.93, 0]} rotation={[0, 0, 2.858]} scale={100}>
                  <mesh name="map_(1)osm_buildings003_wall_0" geometry={nodes['map_(1)osm_buildings003_wall_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                  <mesh name="map_(1)osm_buildings003_roof_0" geometry={nodes['map_(1)osm_buildings003_roof_0'].geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="WATER" position={[0, 0, 289.581]} scale={100}>
                  <mesh name="WATER_water_0" geometry={nodes.WATER_water_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="MOSCOW_CITY" scale={100}>
                  <mesh name="MOSCOW_CITY_wall_0" geometry={nodes.MOSCOW_CITY_wall_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
                <group name="Object002" scale={100}>
                  <mesh name="Object002_wall_0" geometry={nodes.Object002_wall_0.geometry} material={materials['MOSCOW_TEST.FBX']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/city.glb')
